Metronome fix improvements
daschuer/mixxx pull request #97
Opened 2024-09-11 21:02 UTC by Swiftb0y

this is rebased on newest 2.4 so the history is messed up because mixxx would otherwise crash on startup during testing. The only two relevant commits are the last two:

* da5c3feb309559cdd77f16d5198db035d9620837 which looks big but is just moving stuff around.
* df08e9a209e7a68d801e466edf1678b46da50b0c is the only with the (IMO) improvements. It tries to not mixxx abstraction levels as badly. It also reduces the nesting which makes the meaty logic easier to understand. It also adds comments to the edge cases that are currently (as well as in https://github.com/mixxxdj/mixxx/pull/13636) broken. Unfortunately it also has an issue where the click now sounds choppy but I can't figure out why. It _should_ mostly be equivalent to your solution (assuming I understood your code in the first place).

I'd be very grateful if you could take a look soon.

2024-09-11 21:16 UTC, Swiftb0y commented
of course... C++17 skewing me over as always. I'd prefer to retarget this at `main` then.

2024-09-11 23:17 UTC, daschuer requested changes

2024-09-11 23:17 UTC, daschuer commented on src/effects/backends/builtin/metronomeeffect.cpp
> -            SampleUtil::addMonoToStereo(&pOutput[outputOffset * 2], &click[0], copyFrames);
We may play the click twice per call back. First play the remaining click samples from the previous call back. Than start a new click. The later is now gone.

2024-09-12 16:17 UTC, Swiftb0y commented on src/effects/backends/builtin/metronomeeffect.cpp
> +static size_t playMonoSamples(std::span<const CSAMPLE>& monoSource, std::span<CSAMPLE> output) {
yes, but this time it makes sense. We had this discussion a thousand times before. Do you really need me to `#include <gsl/pointers>` just so I can write `gsl::not_null<std::span<CSAMPLE>> monoSource` and `monoSource->data()`? This restriction is based on the google style-guide and [even they dropped it in 2020](https://github.com/google/styleguide/pull/553) (signed off by essentially the authority on their style guide, titus winters)...

The argument that the `&` at the caller indicates that the object will get modified just doesn't make sense when you can perfectly pass a `std::unique_ptr<T>`, `std::shared_ptr<T>`, `std::span<T>`, and even raw `T` by value (or even `const&`) and still mutate it...

2024-09-12 16:18 UTC, Swiftb0y commented on src/effects/backends/builtin/metronomeeffect.cpp
> +static size_t playMonoSamples(std::span<const CSAMPLE>& monoSource, std::span<CSAMPLE> output) {
If you want the mutable borrow from Rust, then we should just transition to Rust already.

2024-09-12 16:24 UTC, Swiftb0y commented on src/effects/backends/builtin/metronomeclick.cpp
> +constinit const CSAMPLE kClick44100[] = {
The initial motivation for making this `constinit const` rather than `constexpr` was to explicitly say that this is not expected to be used in a `constexpr` context. That said:

> Only constexpr asserts that the variable is directly read from the .rodata or .text segment without any runtime initialization.

Why should that not apply to `constinit const` as well?

> If you add const it is the old weak const that can be casted away, with out the assertion to be compile time initialized.

You can easily cast away the const from a `constexpr`, it'll just likely segfault. What distinction in `const` are you referencing?

> The compiler may skip this initialization like it does for any other const according to its optimization settings but without assertion.

I'm certain thats not the case. `constinit` asserts that is is initialized at compile-time. The same is not true for (non-`static`) `constexpr` variables if you really want to be pedantic.

2024-09-12 16:26 UTC, Swiftb0y commented on src/effects/backends/builtin/metronomeeffect.cpp
> -            SampleUtil::addMonoToStereo(&pOutput[outputOffset * 2], &click[0], copyFrames);
I can't follow you here. The second time playing is still here, Its the second call to `playMonoSamples` at the bottom of the function. Only this time is clearer when it actually happens (only when there is actually space in the output buffer for it).

2024-09-12 16:28 UTC, daschuer commented on src/effects/backends/builtin/metronomeeffect.cpp
> +static size_t playMonoSamples(std::span<const CSAMPLE>& monoSource, std::span<CSAMPLE> output) {
In this case you can also return the span and pass it as const reference.

2024-09-12 16:32 UTC, Swiftb0y commented on src/effects/backends/builtin/metronomeeffect.cpp
> +static size_t playMonoSamples(std::span<const CSAMPLE>& monoSource, std::span<CSAMPLE> output) {
yes, though it didn't make the callsite any prettier.

2024-09-12 16:34 UTC, daschuer commented on src/effects/backends/builtin/metronomeclick.cpp
> +constinit const CSAMPLE kClick44100[] = {
> this is not expected to be used in a constexpr context.

What would be the issue? 

I stumbled over it, because for my understanding the reason for constinit is to assert that a non const ist initializer by a const or constexp. Making it const defeats the original purpose.

2024-09-12 16:42 UTC, daschuer commented on src/effects/backends/builtin/metronomeeffect.cpp
> -            SampleUtil::addMonoToStereo(&pOutput[outputOffset * 2], &click[0], copyFrames);
Ok it looks like I don't understand the code anymore. Does if full work now?

2024-09-12 16:54 UTC, Swiftb0y commented on src/effects/backends/builtin/metronomeclick.cpp
> +constinit const CSAMPLE kClick44100[] = {
What would be the issue?

No issue really, just trying to document intent. `constexpr` also works here, though its not required. I was just trying to use the right tool for the job. 

> because for my understanding the reason for constinit is to assert that a non const ist initializer by a const or constexp.

No, its purpose is to _assert_ (as in force the compiler but also allow it to optimize based on the assumption) that a _static_ (doesn't work on non-static) variable is initialized at compile time. Doesn't mean it'll be placed in `.rodata` (though with `const` it will). even the compiler (at least clang) recognizes that `constinit const` and `constexpr` is the same and de-duplicates the static data in the binary.

Anyways, I forgot that this was targeted at non-C++20 compilers, so `constexpr` is the only thing that works in this case.

2024-09-12 16:57 UTC, Swiftb0y commented on src/effects/backends/builtin/metronomeeffect.cpp
> -            SampleUtil::addMonoToStereo(&pOutput[outputOffset * 2], &click[0], copyFrames);
Almost as good as what this is based on. Unfortunately it garbles the next-click sample for a reason I haven't found out yet. I was hoping you could spot it but it seems these changes had the opposite effect (making it easier to understand). At least I was able to spot the bugs I mentioned in the code (see the TODOs I left).

2024-09-12 17:38 UTC, Swiftb0y commented on src/effects/backends/builtin/metronomeeffect.cpp
> -            SampleUtil::addMonoToStereo(&pOutput[outputOffset * 2], &click[0], copyFrames);
figured out the click issue. I will try to fix the remaining issues.

2024-09-13 20:02 UTC, Swiftb0y commented
nice, even works on 2.4

2024-09-15 09:39 UTC, daschuer commented on src/effects/backends/builtin/metronomeeffect.cpp
> +    playMonoSamples(subspan_clamped(click, gs->framesSinceLastClick), output);
Here are to many checks involved until nothing is copied. Let's keep the initial check.

2024-09-15 09:39 UTC, daschuer commented on src/effects/backends/builtin/metronomeeffect.cpp
> +        gs->framesSinceLastClick = playMonoSamples(click, outputBufferOffset);
I do not understand this condition. Does it work when seeking?

2024-09-15 10:00 UTC, Swiftb0y commented on src/effects/backends/builtin/metronomeeffect.cpp
> +std::span<T> subspan_clamped(std::span<T> in, typename std::span<T>::size_type offset) {
[unfortunately not](https://en.cppreference.com/w/cpp/container/span/subspan).

> The behavior is undefined if either Offset or Count is out of range. This happens if
> * Offset is greater than size(), [...]

2024-09-15 10:02 UTC, Swiftb0y commented on src/effects/backends/builtin/metronomeeffect.cpp
> +        gs->framesSinceLastClick = playMonoSamples(click, outputBufferOffset);
Seeking what? The track? How would I test that?
The condition checks if the output buffer is not empty because then our new position to play is within the current buffer. If `playMonoSamples` is actually called here with a nonempty `outputBufferOffset`, then we know a new click has happened so we can just write to `gs->framesSinceLastClick` how many samples we've played.

2024-09-15 10:04 UTC, Swiftb0y commented on src/effects/backends/builtin/metronomeeffect.cpp
> +std::span<T> subspan_clamped(std::span<T> in, typename std::span<T>::size_type offset) {
If we want this clamped/fusing span behavior, I would consider creating wrapper around it. But since we only really needed this for `.subspan` (and `.last`), I didn't go through that effort.

2024-09-15 10:17 UTC, Swiftb0y commented on src/effects/backends/builtin/metronomeeffect.cpp
> +    playMonoSamples(subspan_clamped(click, gs->framesSinceLastClick), output);
[its only two instructions less](https://compiler-explorer.com/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAZgQDbYB2AhgLbYgDkAjF%2BTXRMiAZVQtGIHgBYBQogFUAztgAKAD24AGfgCsp5eiyahUAUgBMAIUtXyKxqiIEh1ZpgDC6egFc2TKQtydwAZAiZsADk/ACNsUhALAGZyAAd0JWIXJi9ff0C0jKyhMIjotjiE5PtsR2chESIWUiJcvwCeIIdsJ2zG5qJSqNj4xJSlJpa2/M77ScHw4YrR5IBKe3QfUlROLksk8NRfHABqMySPJVTjc9wzLQBBe4efTJMTjxEHgFlVENwzkkACInGj0dAsIjnGyPZ7YdREeJME4AN3QBEwJxYmEw3yE6AAKuhGvFsOgIJ8fn9cAAqcgnDBMCYfL6/f50k4TTAgECZABe2AA%2BkRVtDns8APQSk7wxGkZHY3H4okk0hkims6kcyls2n0rk8/lCkVi2GPA28ggC4UnVJGACeeKYxPYduwSggFquNwujOZOuptxObHxIk222w%2BqI3N51yY5w8Af%2BQc2RFSPhFZwA7DCHid8wyhMyvVbjSdU%2BmiFYfDQaPEAGKkdjuwEgisZgB0RogqxO0osprzBZL1qIoKbHCUqgd2Ex5xBFrY4QgIedYa2Oy7pZ79PbVZrddIjebSlFSVzBaxOKdhOJcvVe47mEhLB3wdD4c3z6ab5oE/d04sPas5nheBZqkQWzIn%2BJ6AcBmCDmYWZAuKjyImwdqQtgCZHCwShKCcBK3M8XpxgmRFJACSg%2BDE3pMIKuEYbOnrRoaZEXBRALhPSRD2qkzDNpyrGxj6HicYapbCnx2DlrWKiZkhYH5lKhEAPJAqpJwQCIADuBA0EQMRaPaqwgJySCbPQmI6TJ4QTNg2IMmqWFYicOlNqk/GkCcvH8T5SCQicBAYYwHDCEozyXipChWAAtH%2B2AyZYFiMfxCEWBY5ZeZC2QRUk9aReB2CQfKQVMF2NF0SxMZLkwEDoHJxX0uEW4Cj2qygeKyGoQ84RjqkpDoDs%2BHVWxolJnclHlhmlb0n6Y6kaJ80slSyZTUcBCoAA1lGMZGjaMGTiIhzYCEeGtPQm1bb2ik9ZemGOqGrqMB61G0XGDFGExmAQBt230od7rHUwOxnRMHiXdt6zTWmGadbC3Vmg8XDrPQ3AAKz8AEvD8Og3AeLYticp%2BSXJHw5BENoKPrFtIDo1ohjcNI/BsHTDPYzo5B41w/BKCADOU1wOjrHAsAoBgOD4MQZCUNQdCMKwHDcOTgjCGIEicDIcjCMoaiaELeiJIYximIT1g1HU2RuEwnjeO0BShIs5SVGMhSZPUOR2/k6Nu8UTBDM7KzjLUPQe/0Uxex0XQh70DTzAHIxVOM8zTAEPsTAMCfLEn6xKCT3D7IcxxJRcdHEUjrzhMAK26q2oLgpCiGPLKSKouimKKjeKr3uSE0cstfe7RJo7w08jwqS3pWd8qd6kr3mrsvSg9CXtkkmuePUjmWD03iIz3uqNInxr6RZjhNQarsSJND0fCbn1Ne43TmhX5stW82nu1a1g2/4EfOMOVlatgHsfYTgDg3o8S878xyAynDOOcwIV48lqiuD8G5sBALfJ/A8P8Tyj0vNPZ03c571Rmp2b8r5oaX3XBGJ8L5fy/zgiBQcl4IJQXHLBeBiFEZjweOhTCiIcJGHwoRcuDxFrHzEkGN6dFPqumYhI8iQZuI%2BWkorGSiiOK3GHsaaSskaDySfkpPs0oCTqU0tpPSBkjImTMkoCyPgrJuVskyREjlUDOURK5dyLBPLxFUX5IgAUxzBTdGFIgEVIEFminFBKpMUpfTSslLK8QcpFnOAVKJ%2BY2GlRajIuMh8UENQMU1MqmCOqjyQihJGfVbSDWGq9YSZcLj3wBHuOap8kG3xPq4mugZ1qQx2l0/aMDf7A1BudCGV0jEvyCjQLSsDxmnUmYMwEHgGSDPKTMrJl5bQOl3vvD0f0toVXesYWgYyTpgwutM3cZD17GKqV1IEKNGZcExuQDmuN8ZmysMTdBZxkgWH4ILYW6wkAORwAkHcaMuDM3IKzemnyqZc24LzfmFMqYdXILTaQ6MOwADYACcPAiVaAJVoLQ6MMqkpSLCpIWMUXcxBVi8gotkAgEILWWWtB5Dq0kFrVWigVAaBRfQJAfMeCGAlVygy0kMXipUAiJs6BUgezReQUgEqjZaqULK3ynAGa6tlCqtVVseaowxoyg2qKuBAn0vMgAagQbANlvLqAABwEtigS6QGyTYnB4EkDsWgOw8FRART13rfX%2BveEGkNYaWUGxFuLdAGEGDxB5RgdNjAEi4RMEGrQUr5Zyj5hAGIKKYjhGaPaZW/Aq2sFIPaVSMRdChzreQbN4TVJMHoLWm1OAYg%2BGAB4CQ9A%2BY43IDgNgJtJADoIGqXoKJ3QovhD0DMuxyZ9VqGKggMQmxNq8DgFFRBSDBQ7cu0gMQMjYCBNgGdJhLomFZWCFgwAlDOtdapfi2MVZ8vEAK2QQrdaiptfoKVRhn3mGsLYQwe6%2BaQHWKqj2E7YqqXDbFWKXJ5zQZsNYCwnN0CXrPTgBDO5uixwCBAdwqcDCOzKInAw6R3bZFo1K5jfss4uylRRsOKdI4GF430eOTtGM8f43kDocxM6iezlIXO%2BceCWvedawj3AThRp9X6/N1d42hvDRAKWJBvL7CU0m4WbLU05szVQX6abUgZrzZB4Ahbi0MFLdQCtNqG01o7T5ptLa21OA7V25gRAe19pRYO4do76Djo7dO2duxOaEEXc4ZdE7OZrtQBujt27YWc0uvumtR7ksgrPazSdl7r0qDvQ%2B4AT7QDJoEEYd9n6dLfuYB2oV/LNZAfkCB/WnN9BBGc2gX5cHaLwCQ2aos3A0MYaw9GHDvyCO42IxiFdiGLahyttRm2bHgg2y46MdjRQPaHY4x7E7CQeMxz4wMQ7Qm44yYY3J8Tj2BMfZaDd%2BTGx0GJGUx8r5tqNNeq07G3Twb9NaSM2QQFSQLCrHM9TcgELsSjB3LTdG0gOxJC0B6rQRKkhEqJdILMWZCdZgJW8%2BFrMeCUuRTa5l9gMWgtR7C4FTO1M80xcm9Yl7MiuGkEAA%3D%3D)
It even eliminates the branch completely at `-O1`...

2024-09-15 10:20 UTC, Swiftb0y commented on src/effects/backends/builtin/metronomeeffect.cpp
> +    playMonoSamples(subspan_clamped(click, gs->framesSinceLastClick), output);
also note that `cmovb`'s are cheap because they do not inhibit speculation or create pipeline stalls...

2024-09-15 10:49 UTC, daschuer commented on src/effects/backends/builtin/metronomeeffect.cpp
> +std::span<T> subspan_clamped(std::span<T> in, typename std::span<T>::size_type offset) {
You can just omit the Count patameter and subspan() does the clamping for us.

2024-09-15 10:52 UTC, daschuer commented on src/effects/backends/builtin/metronomeeffect.cpp
> +        gs->framesSinceLastClick = playMonoSamples(click, outputBufferOffset);
Yes, I have tested that in my solution by Brandon's seeks and debug outputs for verifying the output.

2024-09-15 11:02 UTC, daschuer commented
My branch does now contain the essential changes from this IMHO. Since we are now past the 2.4.2 deadline, I would like to proceed with the release locking into the other leftover PRs and issues. Can we merge my branch as it is? 

You may retarget this to main, this way we don't need to deal wirth gsl/span anymore. An open issue is however how we want to proceed with the span refactoring in general. Maybe we need a wrapper to adjust types and alow a frame based logic. This way it is probably possible to replace the hard to understand readable/writable chunk logic in the sound sources. 
This effect is a good ground for a POC.

2024-09-15 11:05 UTC, Swiftb0y commented on src/effects/backends/builtin/metronomeeffect.cpp
> +std::span<T> subspan_clamped(std::span<T> in, typename std::span<T>::size_type offset) {
no it doesn't, not by the standard and also not in practice: Take the libc++ sources for example: it just [does plain pointer arithmatic](https://github.com/llvm/llvm-project/blob/614a064cac4f8d0e9c53fafd7876a71be84b8610/libc/src/__support/CPP/span.h#L99-L101). Note that this is `std::span`, not `gsl::span`.

2024-09-15 11:21 UTC, Swiftb0y commented
> Maybe we need a wrapper to adjust types and alow a frame based logic. This way it is probably possible to replace the hard to understand readable/writable chunk logic in the sound sources.

I agree. that is where `mdspan` would shine. We should definitely encode the buffer layout in the type itself.

2024-09-15 11:28 UTC, Swiftb0y commented on src/effects/backends/builtin/metronomeeffect.cpp
> +        gs->framesSinceLastClick = playMonoSamples(click, outputBufferOffset);
I still can't follow you. What edge case exactly are you referring too?

2024-09-15 13:42 UTC, closed without merging